server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-auth
          uri: http://${USER_SERVICE_HOST:localhost}:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - name: AuthFilter
              args:
                secured: false

        - id: user-service-users
          uri: http://${USER_SERVICE_HOST:localhost}:8081
          predicates:
            - Path=/api/users/**
          filters:
            - name: AuthFilter
              args:
                secured: true

        - id: event-producer-service
          uri: http://${EVENT_PRODUCER_HOST:localhost}:8082
          predicates:
            - Path=/api/events/**
          filters:
            - name: AuthFilter
              args:
                secured: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970



management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always